services:
  projecttrak:
    build: .
    container_name: projecttrak
    restart: unless-stopped
    ports:
      - "8083:3000"
    volumes:
      - /volume1/docker/projecttrak/data:/data
    environment:
      - DB_PATH=/data/projecttrak.db
      - SESSION_SECRET=knlbit8768fye7678gkhjevyfOeUeeYFUYeererECELYCEE
      - SETUP_KEY=hemuOYEFOYFycycelycEUYCEO683R38YIDLZYCcYCgeclueUYDO3863D3OYCCejCdjcld
